name: Generate README with Hype
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Install hype
        run: go install github.com/gopherguides/hype/cmd/hype@rename-module-md

      - name: Run hype
        run: |-
          hype export -format=markdown -f hype.md > README.md
          cat README.md

      - name: Commit README back to the repo
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
